version: 2
jobs:
  build:
    working_directory: ~/futtetennismo
    docker:
      - image: haskell:8.0.2
    branches:
      only:
        - source
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "futtetennismo.cabal" }}
      - run: |
          stack install hakyll
          stack build
      - save_cache:
          paths:
            - ~/.stack-work
          key: deps-{{ checksum "futtetennismo.cabal" }}
      - deploy:
          name: Deploy master to Github Pages
          command: |
            # Build new files
            stack exec site rebuild
            # Get previous files
            git fetch --all
            git checkout -b master --track origin/master
            # Overwrite existing files with new files
            cp -a _site/. .
            #  Commit
            git add --all
            git commit -m "New release (`date '+%F %T %Z'`)"
            # Push
            git config --global user.email circleci@circleci
            git config --global user.name CircleCI
            git push origin master:master
