version: 2
jobs:
  build:
    working_directory: ~/futtetennismo
    docker:
      - image: haskell:8.0.2
    branches:
      only:
        - source
    steps:
      - checkout
      - restore_cache:
          key: stack-work-
      - run: |
          # Install Hakyll
          # update otherwise `make` won't be found
          apt-get update
          # make needed for hlibsass, ssh to push to github
          apt-get --yes install make ssh
          stack install hakyll
      # Save work until here in case `stack build` fails
      - save_cache:
          paths:
            - ~/futtetennismo/.stack-work
            - /root/.stack/
          key: stack-work-hakyll-{{ checksum "futtetennismo.cabal" }}
      - run:
          name: Build site executable
          command: stack build
      - save_cache:
          paths:
            - ~/futtetennismo/.stack-work
            - /root/.stack/
          key: stack-work-full-{{ checksum "futtetennismo.cabal" }}
      - add-ssh-keys:
          fingerprints:
            - "7c:88:b5:87:0f:9d:a9:ed:c8:fb:4d:2e:cc:59:0a:43"
      - deploy:
          name: Deploy master to Github Pages
          command: |
            git config --global user.email circleci@circleci
            git config --global user.name CircleCI
            # Build new files
            stack exec site rebuild
            git checkout master
            # Overwrite existing files with new files
            cp -a _site/. .
            #  Commit
            git add --all
            git commit -m "[`date '+%F %T %Z'`] New release"
            # Push
            git push origin master:master
