version: 2
jobs:
  build:
    working_directory: ~/futtetennismo
    docker:
      - image: futtetennista/hakyll:futtetennismo-0.1.1
    auth:
      username: futtetennista
      password: $DOCKERHUB_PASSWORD  # or project environment variable reference
    branches:
      only:
        - source
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7a:01:16:ae:b5:e9:16:ff:bd:9a:e4:47:ca:a4:04:2b"
      - checkout
      - restore_cache:
          keys:
            - v2-stack-work-{{ checksum "futtetennismo.cabal" }}
            - stack-work-
      - run:
          name: HLint site executable
          command: stack install hlint && stack exec hlint site/
      - run:
          name: Build executable
          command: stack build --flag futtetennismo:-spellcheck
      - save_cache:
          paths:
            - ~/futtetennismo/.stack-work
            - /root/.stack/
          key: v2-stack-work-{{ checksum "futtetennismo.cabal" }}
      - deploy:
          name: Deploy master to Github Pages
          command: |
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            stack exec futtetennismo rebuild
            git checkout master
            git reset --hard origin/master
            git pull --rebase
            # Overwrite existing files with new files
            cp -a _site/. .
            #  Commit
            git add --all
            git commit -m "[`date '+%F %T %Z'`] New release"
            # Push
            git push origin master:master
